#####################################################################
############################# Services ##############################
#####################################################################


############### Database ###############
apiVersion: v1
kind: Service
metadata:
  name: basketdb
spec:
  selector:
    app: basketdb
  ports:
  - port: 6379
    targetPort: 6379

############### Api ###############
---
apiVersion: v1
kind: Service
metadata:
  name: basketapi
spec:
  selector:
    app: basketapi
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30010
  type: NodePort

  


#####################################################################
########################### Deployments #############################
#####################################################################


############### Database ###############
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketdb
spec:
  selector:
    matchLabels:
      app: basketdb
  template:
    metadata:
      labels:
        app: basketdb
    spec:
      containers:
      - name: basketdb
        image: redis:alpine
        ports:
        - containerPort: 6379


############### Api ###############
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: basketapi
spec:
  selector:
    matchLabels:
      app: basketapi
  template:
    metadata:
      labels:
        app: basketapi
    spec:
      containers:
      - name: basketapi
        image: basketapi:latest
        imagePullPolicy: Never
        env: 
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: CacheSettings__ConnectionString
          value: basketdb:6379
        - name: GrpcSettings__DiscountUrl
          value: http://discountgrpc
        - name: EventBusSettings__HostAddress
          value: amqp://guest:guest@rabbitmq:5672
        
        ports:
        - containerPort: 80


