#####################################################################
############################ Services ###############################
#####################################################################

############### Api GW ###############
---
apiVersion: v1
kind: Service
metadata:
  name: ocelotapigw
spec:
  selector:
    app: ocelotapigw
  ports:
  - port: 80
    targetPort: 80


#####################################################################
########################### Deployments #############################
#####################################################################

########## Api GW ##########
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocelotapigw
spec:
  selector:
    matchLabels:
      app: ocelotapigw
  template:
    metadata:
      labels:
        app: ocelotapigw
    spec:
      containers:
      - name: ocelotapigw
        image: ocelotapigw:latest
        imagePullPolicy: Never           
        env:
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        ports:
        - containerPort: 80

